services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=keeper.me
    volumes:
      - keeper.me_pg_data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: keeper.me
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  keeper.me_pg_data:
